### ISSUE TITLE
Kelp rsETH Mainnet Rate Provider

### ISSUE THREAD

**Issue by Zen-Maxi** [balancer/code-review#7]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0x746df66bc1Bb361b9E8E2a794C299c3427976e6C#readContract

### Protocol Documentation

https://kelp.gitbook.io/kelp

### Protocol Audits

https://kelp.gitbook.io/kelp/audits

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by mkflow27** [comment]
@Zen-Maxi 

See the excerpts from my review also here:

### H-01: Part of the pricing pipeline can be upgraded by an EOA. 
The pricing calculation requires an external call to an oracle contract of the allowed assets. The `LRTOracle` reads an asset price via `getAssetPrice`. The target of the external call can be set by calling `updatePriceOracleFor`. Currently 0x7aad74b7f0d60d5867b59dbd377a71783425af47 is allowed to update the oracle target address. Since this is an EOA, the rate Provider is unfit for operations in Balancer pools. 
Recommendation: Set the LRTManager to be a multisig. 

### M-01: Hardcoded stETH price 
The rsETH pricing logic loops over the involved assets pricing oracles. This includes the [pricing oracle for stETH](https://etherscan.io/address/0x4cB8d6DCd56d6b371210E70837753F2a835160c4#code). The price of stETH in the Rate Provider pricing system is set to 1e18 which can pose a risk depending on LIDOs operational staking integrity. 
Recommendation: Consider replacing the hardcoded value to incorporate for example a stETH/ETH Chainlink price feed.

**Comment by marcusblabs** [comment]
Dheeraj | Stader | Kelp, [30 Jan 2024 at 16:31:35]:
Hi @Mkflow, only this multisig now has the privilege to change oracles now

https://app.safe.global/home?safe=eth:0xCbcdd778AA25476F203814214dD3E9b9c46829A1

The other one was the deployer key that’s closely guarded. But we have routed all privileges to just the manager multisig

Also, do you need more clarity on the stEth oracle part?

**Comment by marcusblabs** [comment]
Hey @mkflow27 
I understand that with this updates from the Kelp team, we would be good to go.
Could you confirm?

**Comment by mkflow27** [comment]
@marcusblabs Just merged the review for mainnet. Closing this issue as done: See: https://github.com/balancer/code-review/pull/9

**Comment by mkflow27** [comment]
@marcusblabs Just merged the review for mainnet. Closing this issue as done: See: https://github.com/balancer/code-review/pull/9
